// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    name,
    type,
    currency_code,
    initial_balance_cents,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, type, currency_code, initial_balance_cents, is_active, created_at, updated_at
`

type CreateAccountParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	Type                string      `json:"type"`
	CurrencyCode        string      `json:"currency_code"`
	InitialBalanceCents int64       `json:"initial_balance_cents"`
	IsActive            bool        `json:"is_active"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.CurrencyCode,
		arg.InitialBalanceCents,
		arg.IsActive,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CurrencyCode,
		&i.InitialBalanceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAccount = `-- name: DeactivateAccount :exec
UPDATE accounts
SET
    is_active = false,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, type, currency_code, initial_balance_cents, is_active, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CurrencyCode,
		&i.InitialBalanceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAccounts = `-- name: ListActiveAccounts :many
SELECT id, name, type, currency_code, initial_balance_cents, is_active, created_at, updated_at
FROM accounts
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listActiveAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CurrencyCode,
			&i.InitialBalanceCents,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET
    name = $2,
    type = $3,
    currency_code = $4,
    initial_balance_cents = $5,
    is_active = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, type, currency_code, initial_balance_cents, is_active, created_at, updated_at
`

type UpdateAccountParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	Type                string      `json:"type"`
	CurrencyCode        string      `json:"currency_code"`
	InitialBalanceCents int64       `json:"initial_balance_cents"`
	IsActive            bool        `json:"is_active"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.CurrencyCode,
		arg.InitialBalanceCents,
		arg.IsActive,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CurrencyCode,
		&i.InitialBalanceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
