// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	CurrencyCode        string             `json:"currency_code"`
	InitialBalanceCents int64              `json:"initial_balance_cents"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Payee struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	PayeeID         pgtype.UUID        `json:"payee_id"`
	AmountCents     int64              `json:"amount_cents"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	IsReconciled    bool               `json:"is_reconciled"`
	Note            pgtype.Text        `json:"note"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
