// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayee = `-- name: CreatePayee :one
INSERT INTO payees (
    id,
    name
) VALUES (
    $1,
    $2
)
RETURNING id, name, created_at, updated_at
`

type CreatePayeeParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) CreatePayee(ctx context.Context, arg CreatePayeeParams) (Payee, error) {
	row := q.db.QueryRow(ctx, createPayee, arg.ID, arg.Name)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePayee = `-- name: DeletePayee :execrows
DELETE FROM payees
WHERE id = $1
`

func (q *Queries) DeletePayee(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePayee, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPayeeByID = `-- name: GetPayeeByID :one
SELECT id, name, created_at, updated_at
FROM payees
WHERE id = $1
`

func (q *Queries) GetPayeeByID(ctx context.Context, id pgtype.UUID) (Payee, error) {
	row := q.db.QueryRow(ctx, getPayeeByID, id)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayees = `-- name: ListPayees :many
SELECT id, name, created_at, updated_at
FROM payees
ORDER BY name ASC
`

func (q *Queries) ListPayees(ctx context.Context) ([]Payee, error) {
	rows, err := q.db.Query(ctx, listPayees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payee{}
	for rows.Next() {
		var i Payee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayeeName = `-- name: UpdatePayeeName :one
UPDATE payees
SET
    name = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdatePayeeNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdatePayeeName(ctx context.Context, arg UpdatePayeeNameParams) (Payee, error) {
	row := q.db.QueryRow(ctx, updatePayeeName, arg.ID, arg.Name)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPayeeByNameCaseInsensitive = `-- name: UpsertPayeeByNameCaseInsensitive :one
INSERT INTO payees (
    id,
    name
) VALUES (
    $1,
    $2
)
ON CONFLICT (name) DO UPDATE
SET updated_at = now()
RETURNING id, name, created_at, updated_at
`

type UpsertPayeeByNameCaseInsensitiveParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpsertPayeeByNameCaseInsensitive(ctx context.Context, arg UpsertPayeeByNameCaseInsensitiveParams) (Payee, error) {
	row := q.db.QueryRow(ctx, upsertPayeeByNameCaseInsensitive, arg.ID, arg.Name)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
