// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreatePayee(ctx context.Context, arg CreatePayeeParams) (Payee, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeactivateAccount(ctx context.Context, id pgtype.UUID) error
	DeleteCategory(ctx context.Context, id pgtype.UUID) (int64, error)
	DeletePayee(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteTransaction(ctx context.Context, id pgtype.UUID) (int64, error)
	GetAccountBalance(ctx context.Context, id pgtype.UUID) (GetAccountBalanceRow, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error)
	GetPayeeByID(ctx context.Context, id pgtype.UUID) (Payee, error)
	GetReconciledAccountBalance(ctx context.Context, id pgtype.UUID) (GetReconciledAccountBalanceRow, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error)
	ListActiveAccounts(ctx context.Context) ([]Account, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListPayees(ctx context.Context) ([]Payee, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	ListTransactionsByAccountAndDateRange(ctx context.Context, arg ListTransactionsByAccountAndDateRangeParams) ([]Transaction, error)
	SetTransactionReconciled(ctx context.Context, arg SetTransactionReconciledParams) (Transaction, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCategoryName(ctx context.Context, arg UpdateCategoryNameParams) (Category, error)
	UpdatePayeeName(ctx context.Context, arg UpdatePayeeNameParams) (Payee, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpsertPayeeByNameCaseInsensitive(ctx context.Context, arg UpsertPayeeByNameCaseInsensitiveParams) (Payee, error)
}

var _ Querier = (*Queries)(nil)
