// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id,
    account_id,
    category_id,
    payee_id,
    amount_cents,
    transaction_date,
    is_reconciled,
    note
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, account_id, category_id, payee_id, amount_cents, transaction_date, is_reconciled, note, created_at, updated_at
`

type CreateTransactionParams struct {
	ID              pgtype.UUID `json:"id"`
	AccountID       pgtype.UUID `json:"account_id"`
	CategoryID      pgtype.UUID `json:"category_id"`
	PayeeID         pgtype.UUID `json:"payee_id"`
	AmountCents     int64       `json:"amount_cents"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	IsReconciled    bool        `json:"is_reconciled"`
	Note            pgtype.Text `json:"note"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.AccountID,
		arg.CategoryID,
		arg.PayeeID,
		arg.AmountCents,
		arg.TransactionDate,
		arg.IsReconciled,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.PayeeID,
		&i.AmountCents,
		&i.TransactionDate,
		&i.IsReconciled,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, account_id, category_id, payee_id, amount_cents, transaction_date, is_reconciled, note, created_at, updated_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.PayeeID,
		&i.AmountCents,
		&i.TransactionDate,
		&i.IsReconciled,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, account_id, category_id, payee_id, amount_cents, transaction_date, is_reconciled, note, created_at, updated_at
FROM transactions
WHERE account_id = $1
ORDER BY transaction_date DESC, created_at DESC
LIMIT $2
OFFSET $3
`

type ListTransactionsByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.PayeeID,
			&i.AmountCents,
			&i.TransactionDate,
			&i.IsReconciled,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountAndDateRange = `-- name: ListTransactionsByAccountAndDateRange :many
SELECT id, account_id, category_id, payee_id, amount_cents, transaction_date, is_reconciled, note, created_at, updated_at
FROM transactions
WHERE account_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
ORDER BY transaction_date DESC, created_at DESC
LIMIT $4
OFFSET $5
`

type ListTransactionsByAccountAndDateRangeParams struct {
	AccountID         pgtype.UUID `json:"account_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
	Limit             int32       `json:"limit"`
	Offset            int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByAccountAndDateRange(ctx context.Context, arg ListTransactionsByAccountAndDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccountAndDateRange,
		arg.AccountID,
		arg.TransactionDate,
		arg.TransactionDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.PayeeID,
			&i.AmountCents,
			&i.TransactionDate,
			&i.IsReconciled,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionReconciled = `-- name: SetTransactionReconciled :one
UPDATE transactions
SET
    is_reconciled = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, account_id, category_id, payee_id, amount_cents, transaction_date, is_reconciled, note, created_at, updated_at
`

type SetTransactionReconciledParams struct {
	ID           pgtype.UUID `json:"id"`
	IsReconciled bool        `json:"is_reconciled"`
}

func (q *Queries) SetTransactionReconciled(ctx context.Context, arg SetTransactionReconciledParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, setTransactionReconciled, arg.ID, arg.IsReconciled)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.PayeeID,
		&i.AmountCents,
		&i.TransactionDate,
		&i.IsReconciled,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    account_id = $2,
    category_id = $3,
    payee_id = $4,
    amount_cents = $5,
    transaction_date = $6,
    is_reconciled = $7,
    note = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, account_id, category_id, payee_id, amount_cents, transaction_date, is_reconciled, note, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              pgtype.UUID `json:"id"`
	AccountID       pgtype.UUID `json:"account_id"`
	CategoryID      pgtype.UUID `json:"category_id"`
	PayeeID         pgtype.UUID `json:"payee_id"`
	AmountCents     int64       `json:"amount_cents"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	IsReconciled    bool        `json:"is_reconciled"`
	Note            pgtype.Text `json:"note"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.AccountID,
		arg.CategoryID,
		arg.PayeeID,
		arg.AmountCents,
		arg.TransactionDate,
		arg.IsReconciled,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.PayeeID,
		&i.AmountCents,
		&i.TransactionDate,
		&i.IsReconciled,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
